version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: screenshot_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: screenshot_password_123
      MONGO_INITDB_DATABASE: screenshot_api
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    networks:
      - screenshot_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: screenshot_backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://admin:screenshot_password_123@mongodb:27017/screenshot_api?authSource=admin
      - DB_NAME=screenshot_api
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - PLAYWRIGHT_BROWSERS_PATH=/pw-browsers
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    volumes:
      - ./screenshots:/app/screenshots
      - playwright_browsers:/pw-browsers
    networks:
      - screenshot_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: screenshot_frontend
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - screenshot_network

volumes:
  mongodb_data:
    driver: local
  playwright_browsers:
    driver: local

networks:
  screenshot_network:
    driver: bridge